# =========================================================
#  Dongqin Kill - source bundle for the file:// replay export
#
#  WHY THIS EXISTS
#  A page opened as file:// is not allowed to fetch its own files, so
#  "export a shareable replay" could not read js/*.js or css/*.css when you
#  play by double-clicking index.html -- only when the page is served over
#  http. Loading a file with <script src> IS still allowed from file://, so
#  the sources are shipped as a generated script that net.js loads on demand
#  -- and only after the normal fetch path has failed.
#
#  Over http this file is never touched: fetch reads the real files, which
#  can never be stale. It matters only for the double-click case.
#
#  Regenerate after editing any js/*.js or css/*.css:
#    powershell -ExecutionPolicy Bypass -File tools\build-sources.ps1
#  (build-mobile.ps1 calls this too, so re-running that one keeps both in sync)
#
#  This script must stay ASCII-only: PowerShell 5.1 reads .ps1 as ANSI/GBK.
# =========================================================
param([string]$Out = '')

$ErrorActionPreference = 'Stop'
$tools = Split-Path -Parent $MyInvocation.MyCommand.Path
$root  = Split-Path -Parent $tools
if (-not $Out) { $Out = Join-Path $root 'js\sources.js' }

# Same six modules net.js inlines into an exported replay, in a fixed order so
# the output is byte-identical between runs (the freshness test relies on that).
$jsFiles  = @('data', 'fx', 'ai', 'engine', 'ui', 'net')
$cssFiles = @('style.css', 'mobile.css')

# Line endings are normalised to LF first. The sources are CRLF on disk, and a
# JSON string has to escape both halves (\r\n = 4 chars for one line break,
# \n = 2), which on a 70k-line tree adds ~140 KB for nothing. Newlines still
# have to stay *escaped* -- the sources rely on automatic semicolon insertion.
$js = [ordered]@{}
foreach ($n in $jsFiles) {
  $p = Join-Path $root "js\$n.js"
  if (-not (Test-Path $p)) { throw "missing file: $p" }
  $js[$n] = ((Get-Content $p -Raw -Encoding UTF8) -replace "`r`n", "`n")
}
$css = (($cssFiles | ForEach-Object {
  $p = Join-Path $root "css\$_"
  if (-not (Test-Path $p)) { throw "missing file: $p" }
  (Get-Content $p -Raw -Encoding UTF8) -replace "`r`n", "`n"
}) -join "`n")

$json = ([ordered]@{ v = 1; js = $js; css = $css }) | ConvertTo-Json -Compress -Depth 4

# ConvertTo-Json writes every non-ASCII char as \uXXXX, which inflates a
# Chinese-heavy source tree by ~55% (595 KB vs 384 KB). Turn those back into
# real characters -- the file is written as UTF-8 *with* a BOM, so the browser
# can never guess the encoding wrong when it loads this over file:// (there is
# no Content-Type header there to fall back on).
#   U+2028 / U+2029 stay escaped: they ARE line terminators in JS and would
#   break the string literal. Control chars stay escaped for the same reason.
# The alternation matters: `\\` (an escaped backslash) has to be consumed as a
# unit. Matching bare \uXXXX would let the SECOND backslash of a \\ start a
# match, so any source containing a literal backslash followed by "u" would
# quietly corrupt. That is exactly how the first version of this broke.
$json = [regex]::Replace($json, '\\\\|\\u([0-9a-fA-F]{4})', {
  param($m)
  if (-not $m.Groups[1].Success) { return $m.Value }          # escaped backslash: leave as-is
  $cp = [Convert]::ToInt32($m.Groups[1].Value, 16)
  if ($cp -lt 0x20 -or $cp -eq 0x2028 -or $cp -eq 0x2029) { return $m.Value }
  return [string][char]$cp
})

$marker = 'window.DQK_SOURCES = '
$text = "/* GENERATED by tools/build-sources.ps1 -- do not edit by hand." + "`n" +
        "   Fallback source bundle for exporting a shareable replay from a" + "`n" +
        "   file:// page, which cannot fetch its own js/ and css/ files. */" + "`n" +
        $marker + $json + ";" + "`n"

# UTF-8 WITH BOM -- see the note above.
[System.IO.File]::WriteAllText($Out, $text, (New-Object System.Text.UTF8Encoding($true)))

# ---------------------------------------------------------------- checks
$size = (Get-Item $Out).Length
# Read the raw bytes: passing an encoding to ReadAllText *strips* the BOM, so
# the BOM check below would always fail against the decoded string.
$bytes = [System.IO.File]::ReadAllBytes($Out)
$read  = [System.Text.Encoding]::UTF8.GetString($bytes)

# Chinese round-trip probe: assembled from code points (this file is ASCII-only).
# sCard = 0x4E0A 0x8BFE 0x70B9 0x540D ("shang ke dian ming", a card name)
$probe = [string]([char]0x4E0A + [char]0x8BFE + [char]0x70B9 + [char]0x540D)

$okJson = $false
$roundTrip = $false
try {
  $i = $read.IndexOf($marker)
  $jsonText = $read.Substring($i + $marker.Length).Trim()
  if ($jsonText.EndsWith(';')) { $jsonText = $jsonText.Substring(0, $jsonText.Length - 1) }
  $parsed = $jsonText | ConvertFrom-Json
  $okJson = ($parsed.js.PSObject.Properties.Name.Count -eq 6) -and ($parsed.css.Length -gt 1000)
  # Decode one module back and compare with the file on disk. Escaping bugs
  # (exactly what bit the first version) survive "it parses" but never this.
  $disk = (Get-Content (Join-Path $root 'js\engine.js') -Raw -Encoding UTF8) -replace "`r`n", "`n"
  $roundTrip = ($parsed.js.engine -eq $disk)
} catch { $okJson = $false }

$checks = [ordered]@{
  'written'        = (Test-Path $Out)
  'has-banner'     = ($read.IndexOf('GENERATED by tools/build-sources.ps1') -ge 0)
  'assigns-global' = ($read.IndexOf($marker) -ge 0)
  'json-parses'    = $okJson
  'roundtrip-exact'= $roundTrip
  'all-six-modules'= (($jsFiles | Where-Object { $read.IndexOf('"' + $_ + '":') -lt 0 }).Count -eq 0)
  'cjk-survives'   = $read.Contains($probe)
  # BOM on purpose: file:// gives no Content-Type, so this is what fixes the encoding.
  'has-bom'        = ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)
  'size-sane'      = ($size -gt 200000 -and $size -lt 800000)
  'lf-only'        = ($read.IndexOf([char]0x000D) -lt 0)
}

Write-Host ""
Write-Host ("sources: " + $Out)
Write-Host ("size   : {0:N0} bytes ({1:N1} KB)" -f $size, ($size / 1KB))
$bad = 0
foreach ($k in $checks.Keys) {
  if ($checks[$k]) { Write-Host ("  [ok]   " + $k) }
  else { Write-Host ("  [FAIL] " + $k); $bad++ }
}
if ($bad -eq 0) { Write-Host "ALL CHECKS PASSED" -ForegroundColor Green }
else { Write-Host ("$bad check(s) failed") -ForegroundColor Yellow }
